**Jupyter and Colab Notebooks**

**Jupyter notebooks** let you write and execute Python code locally in your web browser. Jupyter notebooks make it very easy to tinker with code and execute it in bits and pieces; for this reason they are widely used in scientific computing. Easiest way to get jupyter notebooks is by installing Anaconda from https://www.anaconda.com/. 

**Colab** on the other hand is Google’s flavor of Jupyter notebooks that is particularly suited for machine learning and data analysis and that runs entirely in the cloud.

# Numpy #

NumPy stands for Numerical Python and it's a fundamental package for scientific computing in Python. NumPy provides Python with an extensive math library capable of performing numerical computations effectively and efficiently.

## 0. Why Numpy?

In [68]:
import time
import numpy as np

In [69]:
x = np.random.rand(10**8)

In [70]:
start = time.time()
sum(x)/len(x)
print("This operation took ", time.time() - start, "seconds")

This operation took  11.785411834716797 seconds


In [71]:
start = time.time()
x.mean()
print("This operation took ", time.time() - start, "seconds")

This operation took  0.05487680435180664 seconds


## 1. Arrays ##

A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers.

We can initialize numpy arrays from nested Python lists, and access elements using square brackets. 

In [2]:
import numpy as np #Import the numpy library

In [3]:
a = np.array([1, 2, 3]) # Declare an 1-dimensional array
print(a)

[1 2 3]


In [4]:
print(type(a)) 

<class 'numpy.ndarray'>


In [5]:
a[1]

2

In [6]:
print(a.shape) # prints the shape of the array

(3,)


In [8]:
a[0] = 5 #Change an element of the array
print(a)

[5 2 3]


In [9]:
b = np.array([[1, 2, 3], [4, 5, 6]]) #create a two dimensional array

In [10]:
print(b.shape)

(2, 3)


In [11]:
print(b[0,0], b [0,1], b[1,0]) 

1 2 4


In [12]:
print(b[0][0], b[0][1], b[1][0])

1 2 4


In [13]:
a = np.zeros((2,2)) #Create an array of all zeros

In [14]:
print(a)

[[0. 0.]
 [0. 0.]]


In [15]:
b = np.ones((1, 2)) # Create an array of all ones

In [16]:
print(b)

[[1. 1.]]


In [17]:
c = np.full((2,3), 7) #Creates a constant array
print(c)

[[7 7 7]
 [7 7 7]]


In [18]:
d = np.eye(5) #Create a 5x5 identity matrix
print(d)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [19]:
e = np.random.random((2,2))
print(e)

[[0.03973534 0.96682541]
 [0.75556036 0.24215131]]


### Slicing ###

Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array:

In [20]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [21]:
b = a[:2, 1:3]
print(b)

[[2 3]
 [6 7]]


A slice of an array is a view into the same data, so modifying it will modify the original array.

In [23]:
print(a[0,1])
b[0,0] = 77
print(a[0,1])

77
77


You can also mix integer indexing with slice indexing.

In [24]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [25]:
row_r1 = a[1, :] #Extract the second row of a as 1 dimensional array
print(row_r1)
print(row_r1.shape)

[5 6 7 8]
(4,)


In [27]:
row_r2 = a[1:2, :] #Extract the second row of a as 2 dimensional array
print(row_r2)
print(row_r2.shape)

[[5 6 7 8]]
(1, 4)


In [28]:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)
print(col_r2, col_r2.shape)

[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


**Integer array indexing** : When you index into numpy arrays using slicing, the resulting array view will always be a subarray of the original array. In contrast, integer array indexing allows you to construct arbitrary arrays using the data from another array. Here is an example:


In [29]:
a = np.array([[1,2], [3, 4], [5, 6]])
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [30]:
print(a[[0, 1, 2], [0,1,0]])
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))

[1 4 5]
[1 4 5]


In [31]:
# When using integer array indexing, you can reuse the same element from the source array:
print(a[[0, 0], [1, 1]])
print(np.array([a[0, 1], a[0, 1]]))

[2 2]
[2 2]


In [32]:
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [33]:
b = np.array([0,2,0,1])
# Select one element from each row of a using the indices in b
print(a[np.arange(4),b]) 

[ 1  6  7 11]


In [34]:
# Mutate one element from each row of a using the indices in b
a[np.arange(4), b] += 10
print(a)

[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


**Boolean array indexing** : Boolean array indexing lets you pick out arbitrary elements of an array. Frequently this type of indexing is used to select the elements of an array that satisfy some condition. 

In [35]:
a = np.array([[1,2], [3, 4], [5, 6]])
bool_idx = (a > 2) 
print(bool_idx)

[[False False]
 [ True  True]
 [ True  True]]


In [36]:
print(a[bool_idx])

[3 4 5 6]


In [37]:
print(a[a > 2])

[3 4 5 6]


### Arithmetics ###

In [38]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

In [39]:
#Elementwise sum
print(x + y)
print(np.add(x,y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [40]:
#Elementwise difference
print(x - y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [41]:
#Elementwise product
print(x * y)
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [42]:
#Elementwise division
print(x / y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [43]:
#Elementwise square root
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


**Inner Product**

In [44]:
#Inner product of vectors
v = np.array([9, 10])
w = np.array([11, 12])
print(v.dot(w))
print(np.dot(v, w))

219
219


In [45]:
#Matrix/Vector product
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
print(x.dot(v))
print(np.dot(x, v))

[29 67]
[29 67]


In [46]:
#Matrix/Matrix product
print(x.dot(y))
print(np.dot(x, y))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


**Sum**

In [47]:
x = np.array([[1,2],[3,4]])

In [48]:
print(np.sum(x))  # Compute sum of all elements; prints "10"

10


In [49]:
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"

[4 6]


In [50]:
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

[3 7]


**Transponse**

In [51]:
x = np.array([[1,2], [3,4]])

In [52]:
print(x)
print(x.T)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


### Broadcasting ###

Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations. Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.

In [53]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])

In [54]:
print(x)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [55]:
print(v)

[1 0 1]


In [56]:
y = np.empty_like(x) # Create an empty matrix with the same shape as x

In [57]:
# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i:] = x[i:] +v

In [58]:
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [59]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
vv = np.tile(v, (4, 1))

In [60]:
y = x + vv
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [61]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [62]:
np.reshape(np.array([1,2,3]), (3,1))

array([[1],
       [2],
       [3]])

In [63]:
x = np.array([[1,2,3], [4,5,6]])
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)

In [64]:
# Add a vector to each column of a matrix
print((x.T + w).T)

[[ 5  6  7]
 [ 9 10 11]]


In [65]:
# Another solution is to reshape w to be a column vector of shape (2, 1);
# we can then broadcast it directly against x to produce the same
# output.
print(x + np.reshape(w, (2, 1)))

[[ 5  6  7]
 [ 9 10 11]]


Credits: https://cs231n.github.io/python-numpy-tutorial/#jupyter-and-colab-notebooks